apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: vault
  namespace: vault
spec:
  interval: 15m
  chart:
    spec:
      chart: vault
      version: "0.28.0" 
      sourceRef:
        kind: HelmRepository
        name: hashicorp
        namespace: flux-system
  install:
    remediation:
      retries: 3
    createNamespace: true # This makes the separate namespace.yaml optional but good for clarity
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      # This points to the ConfigMap that will be created by our config layer
      name: vault-values
      valuesKey: values.yaml
