---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: grafana-secret
  namespace: grafana
spec:
  encryptedData:
    GF_SECURITY_ADMIN_PASSWORD: AgBmIZUsJAEJnNxjabZnfAihCs04lYTWLqRvkEMYpzz+S4FRhp76oB8SCdE2JH4fOY/Mfh8WKsJCbQsFMDARsO2hTuZE4wKUdHrlWz4C9Dav5OXpFSSSz410+h1FRwM6bxSAh6a6200UMhvnxMJLsu4NcappXnvnrVPN0gSD3m9VYFejO9mI7Dlu4P1nUIet5sDeZDt8vn0OOdXIWZ2OFY56PaxaDYGtaEtMyZ5O6oU/lQxS2N+UNQ2ZtOrV7BbYf88gsI5XssvJK9Ri1vHtnDwH0xAbyjywrLcEJou1BU7S4IuUwy4HHW108wrSXNAau2MmFBcOqGEhu2SWb9DuhmYWDqabr50FveSEOv/9bXYlOCZHHGIJqI10JwnssYsDTb27qSNK2X4En6jUgUvgjwootBxxqZRScizDO1Ey1hizDLS/sTZdqOiuBmLy2VQjMXrFZdbZPdnZTELLpLSZqKk7LDzdeySrjLJ8LdP6bybyLwLVVb2QRaNo06T8gSf9zodAWGvBGt8kvJhjXIkkhX1IXxhaDUt5Gkei4oImsxyalb3dHNaZxgcbDxCqHDOdF/LSkCeihBxxxKfy4ymuN2N8+NUeXxdt9pIQD79dMMSZ46E8e8aeR1D3AysuJnDtJHGec+YCaPRVPNHWnLtoqaHY3U2nkgyKnuY2JY/XqSNc5Iu9Gw+NGckI4l1/0NG3ZivsEwbuktI2cw==
    GF_SECURITY_ADMIN_USER: AgADT3k3qF8FGjQMiq9CI0Mu4JRmiaMPvWAa5vyW3Tm095snjO7r9mPgFrg0iAOoMLsEZRKNl4bKYZmXE2o7qQA7GgV13iAxuvrleB/00yMez3tFuV8YxLDMV8jpjc0GE1khhLxg4aepKzHo4+iw8AxwagcZ8sL6yvIcq1ooXtmXhVK0qEdnJHB1Arpmd78PziJL34hASkK5PwBON4pMZvUlI2In0EAzp/ng85x38SVLtdAPCZQWIhaPYe4ydcrq0qevckAARg6gr32rcZ8oF8LhVvLivEV+iWsakmFSrumMEult5a2KKdu2It5YxXEG+L26jKWavf12EXolwqT+pSCyb+POuFtsYdKRZIY5f2Q3Wjjj6YcY/LdDIAg/HcPpFJFr03GimkxafF6LSUaYna3TjZAHU1xv/3UjQznNBDmn/tan1/ywJ9dZv4S8a2wy91mRTEZuiUMNPMWOoBvqfZ25azlyrEqw5jG5xy9fOpdoe1cI3b0xLPAsGxaAp/PghFrp7/wwsksoDlk2GSkdNQGmc34f7+7DxpA7NCBbicKm4paYjNPj7GE4Sasi1hGDaR6DWafcB6GtRr0rovDXgOBR1XVLx8uqPAl9/CMqtdowT3N390dak9VzTWjpPzsyXm+BmKBDeSlQmulSYaaUiTkeyg1FHo7o5vkrvPgKru1YZWz85WCNrrQC/RVcdQE6jCVPbTBdAg==
  template:
    metadata:
      name: grafana-secret
      namespace: grafana
