apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets-crds
  namespace: external-secrets
spec:
  interval: 15m
  chart:
    spec:
      chart: external-secrets
      version: "0.20.3"
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    crds: Create
  upgrade:
    crds: CreateReplace
  values: {}
