apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: external-secrets
  namespace: external-secrets
spec:
  interval: 15m
  chart:
    spec:
      chart: external-secrets
      version: "0.20.3" 
      sourceRef:
        kind: HelmRepository
        name: external-secrets
        namespace: flux-system
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  
  # CRITICAL: This ensures Vault is ready before ESO tries to install.
  dependsOn:
    - name: vault
      namespace: vault
    - name: external-secrets-crds
      namespace: external-secrets

  valuesFrom:
    - kind: ConfigMap
      name: external-secrets-values
      valuesKey: values.yaml
