apiVersion: apps/v1
kind: Deployment
metadata:
  name: opensearch
  namespace: opensearch
  labels:
    app: opensearch
spec:
  replicas: 1
  selector:
    matchLabels:
      app: opensearch
  template:
    metadata:
      labels:
        app: opensearch
    spec:
      securityContext:
        fsGroup: 1000
      containers:
        - name: opensearch
          image: opensearchproject/opensearch:2.11.0
          envFrom:
            - configMapRef:
                name: opensearch-cm
          ports:
            - containerPort: 9200
              name: http
            - containerPort: 9600
              name: transport
          volumeMounts:
            - name: opensearch-data
              mountPath: /usr/share/opensearch/data
      volumes:
        - name: opensearch-data
          persistentVolumeClaim:
            claimName: opensearch-pvc
