apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: longhorn
  namespace: longhorn-system
spec:
  interval: 15m
  chart:
    spec:
      chart: longhorn
      version: "1.6.2"
      sourceRef:
        kind: HelmRepository
        name: longhorn
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    defaultSettings:
      backupTarget: "https://s3.eu-central-003.backblazeb2.com/HomeLab-Kubernetes-DBs/longhorn/"
      backupTargetCredentialSecret: "longhorn-backup-target-secret"
