repos:
- repo: local
  hooks:
    - id: sops-encryption-check
      name: Check Lab42 Overlays
      entry: |
        /bin/bash -c 'for f in "$@"; do grep -q "sops" "$f" || { echo "ERROR: $f is NOT encrypted!"; exit 1; }; done' --
      language: system
      files: (^|/)lab42/.*\.yaml$
      # Exclude kustomization.yaml files and the cluster/lab42 directory
      exclude: (.*/lab42/kustomization\.yaml$|^cluster/lab42/)
      pass_filenames: true
