repos:
- repo: local
  hooks:
    - id: sops-encryption-check
      name: Check Lab42 Overlays
      entry: |
        /bin/bash -c 'for f in "$@"; do grep -q "sops" "$f" || { echo "ERROR: $f is NOT encrypted!"; exit 1; }; done' --
      language: system
      # This regex now selects all .yaml files in lab42 directories,
      # EXCEPT for files named kustomization.yaml
      files: .*/lab42/(?!kustomization\.yaml$).*\.yaml$
      exclude: ^cluster/lab42/
      pass_filenames: true
