creation_rules:
  # RULE 1: Keep 'base' and 'cluster/lab42' plaintext
  - path_regex: (.*/base/.*|cluster/lab42/.*)\.yaml$

  # NEW RULE: Keep 'kustomization.yaml' in 'lab42' overlays plaintext
  - path_regex: .*/lab42/kustomization\.yaml$

  # RULE 3: Encrypt all other .yaml files in 'lab42' overlays
  - path_regex: .*/lab42/.*\.yaml$
    age: "age1ek6h5yd7d4qs49zyjhu2fsvpwm8a4nezl02gd5zj35cawca5udgqt9jp25"

  # RULE 4: Catch-all to encrypt other manifests
  - path_regex: ^(apps|databases|monitoring|infrastructure)/.*\.yaml$
    age: "age1ek6h5yd7d4qs49zyjhu2fsvpwm8a4nezl02gd5zj35cawca5udgqt9jp25"
