apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: authentik-secret
  namespace: authentik
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: authentik-secret
    creationPolicy: Owner
  data:
    - secretKey: AUTHENTIK_SECRET_KEY
      remoteRef:
        key: homelab/kubernetes/authentik
        property: AUTHENTIK_SECRET_KEY

    # Target local PgBouncer Service
    - secretKey: AUTHENTIK_POSTGRESQL__HOST
      remoteRef:
        key: homelab/kubernetes/authentik
        property: PGBOUNCER_HOST
    - secretKey: AUTHENTIK_POSTGRESQL__PORT
      remoteRef:
        key: homelab/kubernetes/authentik
        property: PGBOUNCER_PORT
    - secretKey: AUTHENTIK_POSTGRESQL__USER
      remoteRef:
        key: homelab/kubernetes/authentik
        property: POSTGRESQL_USER
    - secretKey: AUTHENTIK_POSTGRESQL__NAME
      remoteRef:
        key: homelab/kubernetes/authentik
        property: POSTGRESQL_NAME
    - secretKey: AUTHENTIK_POSTGRESQL__PASSWORD
      remoteRef:
        key: homelab/kubernetes/authentik
        property: POSTGRESQL_PASSWORD
