apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: authentik
  namespace: authentik
spec:
  interval: 5m
  chart:
    spec:
      chart: authentik
      version: '2024.2.1' 
      sourceRef:
        kind: HelmRepository
        name: authentik
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  releaseName: authentik

  values:
    authentik:
      error_reporting:
        enabled: true
        
    postgresql:
      enabled: false 
    redis:
      enabled: false

    # 1. Provide plain-text environment variables here (as a dictionary)
    env:
      AUTHENTIK_REDIS__TLS: "true"
      AUTHENTIK_POSTGRESQL__OPTIONS__SSLMODE: "require"

    envValueFrom:
      AUTHENTIK_SECRET_KEY:
        secretKeyRef:
          name: authentik-secret
          key: AUTHENTIK_SECRET_KEY
          
      # PostgreSQL Secrets
      AUTHENTIK_POSTGRESQL__HOST:
        secretKeyRef:
          name: authentik-secret
          key: POSTGRESQL_HOST
      AUTHENTIK_POSTGRESQL__PORT:
        secretKeyRef:
          name: authentik-secret
          key: POSTGRESQL_PORT
      AUTHENTIK_POSTGRESQL__NAME:
        secretKeyRef:
          name: authentik-secret
          key: POSTGRESQL_NAME
      AUTHENTIK_POSTGRESQL__USER:
        secretKeyRef:
          name: authentik-secret
          key: POSTGRESQL_USER
      AUTHENTIK_POSTGRESQL__PASSWORD:
        secretKeyRef:
          name: authentik-secret
          key: POSTGRESQL_PASSWORD
          
      # Redis/Valkey Secrets
      AUTHENTIK_REDIS__HOST:
        secretKeyRef:
          name: authentik-secret
          key: REDIS_HOST
      AUTHENTIK_REDIS__PORT:
        secretKeyRef:
          name: authentik-secret
          key: REDIS_PORT
      AUTHENTIK_REDIS__USERNAME:
        secretKeyRef:
          name: authentik-secret
          key: REDIS_USERNAME
      AUTHENTIK_REDIS__PASSWORD:
        secretKeyRef:
          name: authentik-secret
          key: REDIS_PASSWORD
