apiVersion: v1
kind: Service
metadata:
  name: graylog
  namespace: graylog
spec:
  selector:
    app: graylog
  ports:
    - name: http
      protocol: TCP
      port: 9000
      targetPort: http
    - name: gelf-udp
      protocol: UDP
      port: 12201
      targetPort: gelf-udp
    - name: syslog-udp
      protocol: UDP
      port: 5140
      targetPort: syslog-udp
