apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: main-pool
  namespace: kube-system
spec:
  blocks:
    # 192.168.100.129 - 192.168.100.190
    - cidr: "192.168.1.128/26"
  serviceSelector:
    matchLabels:
      cilium-lb-pool: main-pool
