apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-secret
  namespace: grafana
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: grafana-secret
    creationPolicy: Owner
  data:
  - secretKey: GF_SECURITY_ADMIN_USER
    remoteRef:
      key: kubernetes/grafana
      property: GF_SECURITY_ADMIN_USER
  - secretKey: GF_SECURITY_ADMIN_PASSWORD
    remoteRef:
      key: kubernetes/grafana
      property: GF_SECURITY_ADMIN_PASSWORD
