apiVersion: longhorn.io/v1beta2
kind: BackupTarget
metadata:
  name: default
  namespace: longhorn-system
spec:
  backupTargetURL: s3://HomeLab-Kubernetes-DBs@eu-central-003/longhorn
  credentialSecret: longhorn-backup-target-secret
