apiVersion: longhorn.io/v1beta2
kind: RecurringJob
metadata:
  name: snapshot-hourly
  namespace: longhorn-system
spec:
  cron: "0 * * * *"
  task: "snapshot"
  retain: 48
  groups:
  - default
  labels:
    longhorn-backup: "true"

