apiVersion: apps/v1
kind: Deployment
metadata:
  name: n8n
  namespace: n8n
  labels:
    app: n8n
spec:
  replicas: 1
  selector:
    matchLabels:
      app: n8n
  template:
    metadata:
      labels:
        app: n8n
    spec:
      nodeSelector:
        role: worker
      containers:
        - name: n8n
          image: n8nio/n8n:1.113.3
          env:
            - name: DB_TYPE
              value: postgresdb
            - name: DB_POSTGRESDB_PORT
              value: "5432"
            - name: N8N_PORT
              value: "5678"
            - name: N8N_SECURE_COOKIE
              value: "false"
          envFrom:
            - secretRef:
                name: n8n-secret
          ports:
            - containerPort: 5678
              name: http
