apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: databases
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 1m
  timeout: 15m # DBs like OpenSearch take a long time to initialize on RPi
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./databases/data
  prune: true
  # wait: true # NOTE: Apps will not start until DBs are "Running"
  # dependsOn:
  #   - name: infrastructure-controllers
  #   - name: infrastructure-configs
