apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: sops-age
  namespace: flux-system
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store
  target:
    name: sops-age
    creationPolicy: Owner
  data:
  - secretKey: age.agekey
    remoteRef:
      key: homelab/kubernetes/sops-age
      property: PRIVATE_KEY
