provider: cloudflare
interval: 10m

# This tells ExternalDNS to create CNAMEs pointing to tunnel 
# instead of looking for a LoadBalancer IP
connectorSource: true 

# Critical for Cloudflare Tunnels
extraArgs:
  - --cloudflare-proxied # Enabled "Orange Cloud" by default
  - --source=ingress
  - --source=service
  - --domain-filter=codewithakay.dev
  - --ingress-class=cloudflare-tunnel

# Map your secret to the standard way the chart expects it
env:
  - name: CF_API_TOKEN
    valueFrom:
      secretKeyRef:
        name: cloudflare-dns-api-token
        key: cloudflare-dns-api-token

