apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: grafana-oidc-secret
  namespace: monitoring
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: grafana-oidc-secret
    creationPolicy: Owner
  data:
    - secretKey: GRAFANA_ADMIN_PASSWORD
      remoteRef:
        key: homelab/kubernetes/grafana
        property: GRAFANA_ADMIN_PASSWORD
    - secretKey: OAUTH_CLIENT_ID
      remoteRef:
        key: homelab/kubernetes/grafana-oidc
        property: OAUTH_CLIENT_ID
    - secretKey: OAUTH_CLIENT_SECRET
      remoteRef:
        key: homelab/kubernetes/grafana-oidc
        property: OAUTH_CLIENT_SECRET
