---
# Peer Configuration (Link happens in the families block)
apiVersion: "cilium.io/v2"
kind: CiliumBGPPeerConfig
metadata:
  name: opnsense-peer-config
spec:
  timers:
    holdTimeSeconds: 90
    keepAliveTimeSeconds: 30
  families:
    - afi: ipv4
      safi: unicast
      advertisements:
        matchLabels:
          advertise: "unifi"

---
#  Cluster Config (Matches all nodes via hostname check)
apiVersion: "cilium.io/v2"
kind: CiliumBGPClusterConfig
metadata:
  name: opnsense-peering
spec:
  nodeSelector:
    matchExpressions:
      - {key: kubernetes.io/hostname, operator: Exists}
  bgpInstances:
    - name: "vlan-40-instance"
      localASN: 64513
      peers:
        - name: "opnsense-router"
          peerAddress: "192.168.40.1"
          peerASN: 64512
          peerConfigRef:
            name: "opnsense-peer-config"

---
# Advertisement (Matches your specific service)
apiVersion: "cilium.io/v2"
kind: CiliumBGPAdvertisement
metadata:
  name: unifi-ad
  labels:
    advertise: "unifi" # Matches the PeerConfig selector above
spec:
  advertisements:
    - advertisementType: "Service"
      service:
        addresses:
          - LoadBalancerIP
      selector:
        matchLabels:
          io.cilium/network: mgmt
          # Force Cilium to look in the unifi namespace
          io.kubernetes.service.namespace: unifi
