apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: k8s-apps-pool
spec:
  blocks:
    - start: "192.168.40.5"
      stop: "192.168.40.10"
  allowFirstLastIPs: "No"
  serviceSelector:
    matchExpressions:
      - {key: io.cilium/network, operator: NotIn, values: [mgmt]}
---

apiVersion: "cilium.io/v2alpha1"
kind: CiliumLoadBalancerIPPool
metadata:
  name: unifi-mgmt-pool
spec:
  blocks:
    - start: "192.168.30.10"
      stop: "192.168.30.10"
  serviceSelector:
    matchLabels:
      io.cilium/network: mgmt
