apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ip-pool.yaml
  - l2policy.yaml
configMapGenerator:
- name: cilium-values
  files:
  - values.yaml
generatorOptions:
  disableNameSuffixHash: true
