apiVersion: apps/v1
kind: Deployment
metadata:
  name: karakeep
  namespace: karakeep
  labels:
    app: karakeep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: karakeep
  template:
    metadata:
      labels:
        app: karakeep
    spec:
      containers:
        - name: karakeep
          image: ghcr.io/melo/karakeep:latest
          ports:
            - containerPort: 8080
              name: http
          envFrom:
            - secretRef:
                name: karakeep-secret
          volumeMounts:
            - name: data
              mountPath: /data
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: karakeep-data
