apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: cilium
  namespace: kube-system
spec:
  interval: 15m
  chart:
    spec:
      chart: cilium
      version: 1.18.4
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  values:
    kubeProxyReplacement: true
    l2announcements:
      enabled: true
    externalIPs:
      enabled: true
    hubble:
      relay:
        enabled: true
      ui:
        enabled: true
    loadBalancer:
      algorithm: maglev
    ipam:
      mode: kubernetes
    ingressController:
      enabled: true
      service:
        type: LoadBalancer
        loadBalancerMode: shared
