apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo
  namespace: graylog-db
  labels:
    app: mongo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mongo
  template:
    metadata:
      labels:
        app: mongo
    spec:
      containers:
        - name: mongo
          image: mongo:5.0
          envFrom:
            - secretRef:
                name: mongo-secret
          ports:
            - containerPort: 27017
              name: mongo
          volumeMounts:
            - name: mongo-storage
              mountPath: /data/db
      volumes:
        - name: mongo-storage
          persistentVolumeClaim:
            claimName: mongo-pvc


