---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: mongo-secret
  namespace: graylog-db
spec:
  encryptedData:
    MONGO_INITDB_ROOT_PASSWORD: AgBJY0P+k4cr7qC1CIjx1xsNdq6TcocekSx8ZKFJu/+Hz+7I0/0Y54os2xFf91OsDAxWaJt/jZM12K+EL6pMAUDNE/dr8p4AxzGn8h66w7KRYNHmuEYTw3FOvYNdCtZ5ve2E6futiRUmJTSJWqCaxeilbAuhyUcADA0oSPax/5pv7tFF1mS6z+RsSohi1U/0MNxd8stZnd9JVg8fQmV1MjaFRVOUD8dLGKO8Kl58IbiOr6RRBFf68HRC/JgxDteBXcf9T3rNny8tCXVYLC/qFUmjAlnoOy8wGQ2U3P52LTNYodw+3syOU2K7LxyG8dDiZ7EKH+TXsljuyjnRHSJkAZQqQyIYsF9c8L3fe9GgsrMxU1/0fA81l4SohiqT/yikBPnyCHlPuztBqaoY/Nssr06ldrmj+i0NLyihENJ7QM6viw+w7VThbVs/3wFGhIiDbAtReOvrS6Y9UlO2Cni6TAQwJdC7kHQcAi3mnxwmuPOtno2NEHij5SgME5ydK5YhJf1lisyZnKqGJQrugWFz1qZM6479t6lnnmsh1P8GrfYYPVYNsw33qZ7NdqBBVUlFJvyQv7tCvUi8/DewUmgUomrRHSFKy7rnTG2ucCZ2jAYv/xLYuSAvF/IaW6G+Jo91BmQPLp0aBvIlFtR3e+DG3J+iVjqCnV0yQTaYM/H7uNCENBjNS+DfWIUkz4zgzF+CD2BXlqQXOM623c8kUmMzObHgvzrQ
    MONGO_INITDB_ROOT_USERNAME: AgCNDN8eiPw68JlEXZ+3v657Oi4C+xzaae9IECDAZ+eHERltHpNlh3oh9L0ROkWwQGV/Re2VIICQMNX3sq42r0nWN6Bkus+UsCIOiEhQSkKCTYUzRCr0DAwaC7H5hvlIXUrEk2FiFaQL6GwvhysYp2EFLgg111rNFMq+LMziXNnyb8fh4zlOLHP2ZE89JqwQXpYdgSGTUGmxHM+zZTMd0cPUyZa+XcNtYgRle6Ambh0Hd+4LLMqBaP+P9w1KYxPM9QDI60rJtjPuKDKnOMdanSo45aoWLnz9fsb6Pn8P+VNKkwJfZ+016nb16cPT2npEeQdT7y9IPTTeTY6pICcDq+v0W9q4ANdi+UM70B2TtEbBQSe5R/kalms6+7nrkUhoZxeq0q92Cv7KH1KNlCHMZ8umVBVbRZho0c+kECqtMr74d0T7iMPt+xLDQ9c3ZDQG50MZakLAaGdgxxbCUMhQdSn8TiPnrhlxFY3rTQXEyKq7b0+gQoit8dT6A39vj1TLlU9OnlFx9O/qf2r5yR0UP1+igR/g2Z1CtL5g5+A6RLv9QV5Vjqg7fyjl1rcOr4j7e2f1VrjI4bAnCj+9pwuIHqiLUKMOLE7xInkG8KpA2w/HVNfWx/897Y/8hcdN/bn+6YlezwTY8dEmZtQMlsSXSjjzcaFc8l7Jc/absu++qW1FNp/IvQWqPcPA6RAZi4eJqtw1ku4YGhMN
  template:
    metadata:
      creationTimestamp: null
      name: mongo-secret
      namespace: graylog-db
