apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: monitoring
resources:
  - ingress.yaml
configMapGenerator:
- name: loki-values
  files:
  - values.yaml
generatorOptions:
  disableNameSuffixHash: true
