loki:
  deploymentMode: SingleBinary
  resources:
    requests:
      cpu: 250m
      memory: 512Mi
    limits:
      cpu: 1
      memory: 1Gi
  persistence:
    enabled: true
    storageClassName: "longhorn"
    size: 10Gi
  ingress:
    enabled: false

promtail:
  enabled: false

grafana-agent:
  enabled: false

grafana:
  enabled: false
  sidecar:
    datasources:
      enabled: false
