apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: taskchampion-sync-server-pvc
  namespace: taskchampion
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
