apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
  namespace: wallabag
spec:
  replicas: 1
  strategy:
    type: Recreate 
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
        try: "0"
        policy-type: "app"
    spec:
      securityContext:
        fsGroup: 65534 # Assigns 'nobody' group permissions to the PVC volume
      initContainers:
        # Permission & Directory fixer container (creates required subdirectories and sets ownership)
        - name: fix-permissions
          image: busybox:latest
          command:
            - "sh"
            - "-c"
            - "mkdir -p /var/www/wallabag/data/db /var/www/wallabag/data/assets /var/www/wallabag/data/images && chown -R 65534:65534 /var/www/wallabag/data && chmod -R 775 /var/www/wallabag/data"
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: data
              mountPath: /var/www/wallabag/data

        - name: wallabag-install
          image: ghcr.io/wallabag/docker:2.6.10
          # command: ['/bin/sh', '-c', 'SYMFONY_ENV=prod bin/console wallabag:install --no-interaction']
          envFrom:
            - secretRef:
                name: wallabag-secret
          volumeMounts:
            - name: data
              mountPath: /var/www/wallabag/data
      containers:
        - name: wallabag
          image: ghcr.io/wallabag/docker:2.6.10
          securityContext:
            allowPrivilegeEscalation: false
          envFrom:
            - secretRef:
                name: wallabag-secret
          ports:
            - containerPort: 80
              protocol: TCP
          volumeMounts:
            - name: data
              mountPath: /var/www/wallabag/data
      restartPolicy: Always
      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: wallabag-pvc
