apiVersion: apps/v1
kind: Deployment
metadata:
  name: wallabag
  namespace: wallabag
  labels:
    app: wallabag
spec:
  replicas: 1
  selector:
    matchLabels:
      app: wallabag
  template:
    metadata:
      labels:
        app: wallabag
    spec:
      containers:
        - name: wallabag
          image: wallabag/wallabag:latest
          ports:
            - containerPort: 80
              name: http
          env:
            - name: SYMFONY__ENV__DATABASE_DRIVER
              value: "pdo_pgsql"
            - name: SYMFONY__ENV__DATABASE_HOST
              value: "postgres.wallabag-db.svc.cluster.local"
            - name: SYMFONY__ENV__DATABASE_PORT
              value: "5432"
            - name: SYMFONY__ENV__DATABASE_NAME
              value: "wallabag"
            - name: SYMFONY__ENV__DATABASE_USER
              value: "wallabag"
            - name: SYMFONY__ENV__DATABASE_PASSWORD
              value: "wallabag-pg-password"
            - name: SYMFONY__ENV__DOMAIN_NAME
              value: "http://cwk.wallabag"
          volumeMounts:
            - name: wallabag-data
              mountPath: /var/www/wallabag/web/assets/images
      volumes:
        - name: wallabag-data
          persistentVolumeClaim:
            claimName: wallabag-pvc


