apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: wallabag-secret
  namespace: wallabag
spec:
  refreshInterval: 1h
  secretStoreRef:
    kind: ClusterSecretStore
    name: aws-secret-store
  target:
    name: wallabag-secret
    creationPolicy: Owner
    template:
      data:
        # Crucial for asset rendering and CORS:
        SYMFONY__ENV__DOMAIN_NAME: "http://cwk.wallabag"
        SYMFONY__ENV__SERVER_NAME: "cwk.wallabag"
        
        # Database Settings:
        SYMFONY__ENV__DATABASE_DRIVER: "pdo_pgsql"
        SYMFONY__ENV__DATABASE_HOST: "postgres.wallabag-db.svc.cluster.local"
        SYMFONY__ENV__DATABASE_PORT: "5432"
        SYMFONY__ENV__DATABASE_NAME: "{{ .POSTGRES_DB }}"
        SYMFONY__ENV__DATABASE_USER: "{{ .POSTGRES_USER }}"
        SYMFONY__ENV__DATABASE_PASSWORD: "{{ .POSTGRES_PASSWORD }}"
  dataFrom:
  - extract:
      key: homelab/kubernetes/wallabag
