apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-pvc
  namespace: wallabag
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
