apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    serviceDiscovery:
      ingress: false
    providers:
      longhorn:
        url: https://cwk.longhorn
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - HomeLab:
        - pgAdmin:
            href: http://cwk.pgadmin/
            description: Database GUI
            icon: pgadmin.svg
        - Network:
            - Pi-hole:
                href: http://cwk.pihole/admin/
                description: Ad-blocking DNS
                icon: pi-hole.svg
                widget:
                  type: pihole
                  version: 6
                  url: http://pihole.pihole/
                  key: "{{HOMEPAGE_VAR_PIHOLE_WEBPASSWORD}}"
            - Unifi:
                href: https://192.168.1.133:8443/
                description: Unifi Controller
                icon: unifi.svg
        - Cluster Management:
            - Longhorn:
                href: http://cwk.longhorn/
                description: Cluster Storage Management
                icon: longhorn.svg
            - Graylog:
                href: http://cwk.graylog/
                description: Log Management
                icon: graylog.svg
    - Misc:
        - Reading:
            - Wallabag:
                href: http://cwk.wallabag
                description: Read later application
                icon: wallabag.svg
        - Automation Tools:
            - n8n:
                href: http://cwk.n8n/
                description: Workflow Automation
                icon: n8n.svg

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
        expanded: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
