apiVersion: v1
kind: ConfigMap
metadata:
  name: homepage
  namespace: homepage
  labels:
    app.kubernetes.io/name: homepage
data:
  kubernetes.yaml: |
    mode: cluster
  settings.yaml: |
    serviceDiscovery:
      ingress: false
    providers:
      longhorn:
        url: https://cwk.longhorn
  custom.css: ""
  custom.js: ""
  bookmarks.yaml: |
    - Developer:
        - Github:
            - abbr: GH
              href: https://github.com/
  services.yaml: |
    - HomeLab:
        - Pi-hole:
            href: http://cwk.pihole/admin/
            description: Ad-blocking DNS
            icon: pi-hole.svg
            widget:
              type: pihole
              version: 6
              url: http://pihole.pihole:80/
              # url: http://pihole.pihole.svc.cluster.local
              key: "{{HOMEPAGE_VAR_PIHOLE_API_KEY}}"

    - My First Group:
        - My First Service:
            href: http://localhost/
            description: Homepage is awesome

    - My Second Group:
        - My Second Service:
            href: http://localhost/
            description: Homepage is the best

    - My Third Group:
        - My Third Service:
            href: http://localhost/
            description: Homepage is 😎
  widgets.yaml: |
    - kubernetes:
        cluster:
          show: true
          cpu: true
          memory: true
          showLabel: true
          label: "cluster"
        nodes:
          show: true
          cpu: true
          memory: true
          showLabel: true
        expanded: true
    - search:
        provider: duckduckgo
        target: _blank
  docker.yaml: ""
