apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: homepage-secret
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: homepage-secret
    creationPolicy: Owner
  data:
  - secretKey: PIHOLE_WEBPASSWORD
    remoteRef:
      key: homelab/kubernetes/homepage
      property: PIHOLE_WEBPASSWORD
