---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-secret
  namespace: homepage
spec:
  encryptedData:
    PIHOLE_WEBPASSWORD: AgBsVtUelbAKOFcyu4XkCeM4ffKV41R+rnX7tZFYh1E+soy8AX2+uOa9vuu2HZBq1lNtBW00p7MWuLMT4Y/3kuNTWRX6sgpjkPG0P8kug4/ayl9VYQGKCtoEeGcjPwuEdMJxbL55RAqHZHW1/EI8KUhNUrz3R2qIxKPhKIvNvCYflNuyRG8c+OaqbReK4KCjX3Uf8lnoKJyg7YXkx5/hl3sTfqqbkQiEN8E6erMTcTJLdZ4JSohHuyYQP0urWjoWZsS6pLsgx2R5fhN8LfiqYbGC4nlJIweanHVOB7sYt5+qyVlL4c3omajFK7ZM15mDofNiCHlAWDlmSDDrDt5EHfzeUNzV3DmQ6fU9oSMHCOpaV/UtAyH0UHatJQMYJBVwPhQkmSJ5oWHJ21p0JiOUIN0BzwYJfInw8GLclLC5L4KC1qm0J4/YJmVgWB/Gb8FCL4qszRYjEDkcSvdiJdY0y7u18TOZgdAszCEgtZvmp1rhZTr+Bewo3kuAToliIUDPwJetyXh8hH8ayzqVao4nyvu2qKe3OXUTP5yq/LIl8cQ20VTkTUglODUMGLfaWd0VkjPvZdsjzu6FK9o0+tqnKihw6ZmeKx/1TN5LYnpGnBOdC53EVCGNVHViThv525tYHGAkm9gvKt+uOLALYx6ypVnTXO3WCPp09AStjb+yoll1wLXDLh0bgHUcJg/C4hgVK3tz3jaCkcIKoxNCKek=
  template:
    metadata:
      creationTimestamp: null
      name: homepage-secret
      namespace: homepage
