---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-secret
  namespace: homepage
spec:
  encryptedData:
    PIHOLE_API_KEY: AgCRj79gGYWazi/CZoj7gpr2wcIJXPc6rIDffAi9J/wKhQ3RWvDIl4901Z5eHDQ64nCBGsIFfl31Burr6bYiRRiF8aBcAqGkhrc1WXsaBAivl3z0uL4ShJA8cEJVH3mdooNZcKpt74eOiMye5Dmr4oiVGA9RaE4cacAuPVQVG3PxAtPwQlzTRa+nbPKNrKD64CS3SAvPGVodGyUwga8WCsKwis8xzwEqW7ztSKTwSG+DJKDiG9QoIdEmSlsO1NOuSM9fE+GdvdHGJIPHwsLSv03ikE9+WZWm93f28kE6wSTnJX/STMVXzNqTJFsnKk71jVQy+4f1zQSWID76MXJlurH7vkbTuGVBiceZiHDaxS8UykdZsAYUZRjFiu0FEnZ+DBMePRGFMBlxRJ/65LEk50RKRRzee25j9x6Ug0YPMFBzlZPxNw3KgC5e9x1ukE5KZ4UvDxB/6rckMzX4pQII3qNRR739MW7DcScj6qNRgKnfsmT/vkkgI+yPXsGjTg0SeG9sm/OqL4FGvgZotiFHImUFljy9EV2TfG90RzI9+CyKz6FDh4dBzaEu69HYG/atf4G1LLHEdfxnZ7SWcFP3hRdsUPYA8SmTnS1pxp8wr3GLykcUc6HEHWKUMBERXRfHhRvj1h4GNWKVPMPuWcbLMPHnN9FQpsKosOP2rRwKRbaoUya0GedxoqD+TXrrVaNUj0GKw2R7hyOZ6VyY0Bt0bL5qi1nFfEJDE5HvB+F7UZDcGAHYMFzLV0Vv7jMkZg==
  template:
    metadata:
      creationTimestamp: null
      name: homepage-secret
      namespace: homepage
