---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: homepage-secret
  namespace: homepage
spec:
  encryptedData:
    PIHOLE_WEBPASSWORD: AgBviYuU8hwI8a5Mh4ehzcn20zsprupM5k96CY5WDpGau3Zv3gqNABeHRX1vUOZXH5ZOLA1tHLvhg/Wc+EEUQIj3DwnV/ixaB9IUbIP5Y1vN3+bRvhYxPdsQ5pZ33tlZ+vWB3qLNvJUdh/1er5iMhHxlxN6vfMrG9nPlfXpeuzBeYt466hh8gdZ1YEmkJdRDfyWnIwuXuw72lQLgLocgebHynxHT49U2tCx05eUMsvdnQH9fy1n3OmrChsQRi5MJqQllmK7QZ9jjZy3/MibRlv/al1KR4zKbcAXhvZR+vGnkuaf4+ehoOTwUKWDTtmp+OUVfgTC5fpmtdxgfY4USQ2NhPSUhd9/LbpE4n/KYIImF0JlFf0h7wcXQbHeHLwMqRbmg5QIJyw8lxmI76DojRLDrvB3t3BGJCEj+x/Rbct7K9Zxhkfc8YlvEGJLtNogqr1qKPxlMwNZjxI4LKPbvYCvZfFPModjhBxQE/G9gMneQQ/f8z5e1PP4ATcL7PYLWqp+yhdj9lSvTk0vCSPQqfwDWsZsurH7mw05nsOVW2A3R731GeJE5iqN96+c6MwH4RK0V6gB8S6nwSr4S+VvbZUZ03qPziMPVfwJLCYEWI7mDszALnxqGqZBU2y9aatPOVhSUjxY+2in0hNlFynFMNNX1YWiRRqpaxYdbRaIrPEm7zojTHV1QZcXkJ5WnnKnS6CfQVxYYe1ayzBPSF9s=
  template:
    metadata:
      creationTimestamp: null
      name: homepage-secret
      namespace: homepage
