apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: pihole-tls
  namespace: pihole
spec:
  secretName: pihole-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
    - cwk.pihole
    - pihole.pihole.svc.cluster.local
