apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-config
  namespace: pihole
data:
  TZ: "Europe/London"
  DNS1: "1.1.1.1"
  DNS2: "1.0.0.1"
  CORS_HOSTS: "pihole.pihole,pihole.pihole.svc,cwk.pihole"
