apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pihole-secret
  namespace: pihole
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pihole-secret
    creationPolicy: Owner
  data:
    - secretKey: WEBPASSWORD
      remoteRef:
        key: kubernetes/pihole
        property: WEBPASSWORD
