---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgCVe/4yGhehn/65RgGMcbxHVwuyVXj20lxxypfTY/NW4lTkrb9dXigMsqvSsvr/z59HApYt22lv1uJtUxDVTPL2q68+0wSEVHiaOgY6FllZy4mzLaEZuSAKVas5wYzclLH4ZhOucvmQHjloVTdgmWbZOnKckG9cMNLifavlnZeprlfqMwPucAm8DV/l3ITMEhMQG2gzzjHboO69et99PtU/9w7FosoU/LVw2EAfBdkYloAcF7oTEkOVOR68RuhUzKFnOks4vvPF+SMPB+qCLkPAv8oTegpV+2k6CxwV9B/czbF4wRW7ZHl//71umog6GpEGPCdYD9fwFmoz4Hd0VUTt5PBvN3rgbrHRan0MPD4jGZNXb+evLtP/iZLNiPZVpw4vXqEmKXZzoHOyxAogRof3QkAADwtXwoBICtMERnJ35A7i3595qZYPGoFp8KCaaYaqY+L8lJDNFRGRVy54+QzRRcZbqWqTEOFZi0TYho0Ra96OscN1VgxKypN6IfYeyW4QXBohYmc7YjWLVGKnXoOieGA5spmozLyNrGlYFpPajciVibvTlhDGiGbBe9pVMag4/KFnDo6+nV+czHXxS3Aqij3oaUoRSq5AszbGS/+GsDn7dIqRd1oia3yegYYsbexYF3bL8JNeS6Suh8n5Xb6MGMCesVLURaRJ9gzf2M5N5QZI73FYZX9XZ8t8lgNxa7OPkddsydH+sb0ugw4=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: pihole
