---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgBB2LWENMMwjNp3tMpmIJbEmpznMz05bohmT3ZfRiFkLKkp9IL7tJ7LktwH9k7Hgh4LU3yQUAJCp/ZuXVvz/MZEvyTzYJxceb0Pj9tGuiCzZujG7qBZSTdgr9q1BkZbUg1r1Jc0IMa336cKdfCBy4SjVSqwweIezhQ6fVtS4KZx3FBqGuCkS3Sf8GkwzkK5zLHS3oDEDtK7LMir3Z8f9KM7BZf4cE4NXtFPYJeW815fGUCgtxpe3iR+gmMgaT47Zr7WJx5XrpysDX1Z4cWodpCfCzVC3eFYL96kZpS6j+RLoDKeRHfC7hZXe6BsT1PLMvK4oqv7SuIyJk8+bROwEi1SsaH7mHTRxJ3sagqLJzAOUCxGZXnvTWv/Pv06oSFmXivsSrl6q/+KjeHYJN1MV4i0+7wvyL7RcTjR/NadLg4u/qXP8nqt0ayEUdtCKJV+Dfluc77+xwBC/aPj9etIUWahlFUxy9kPA74lGVkj2uBD4DoRJR1seVVWr/Nwjb/7+Ec78VSa57dSqyZKAXT9MtpGCJGE3qsCsTXNGRrQ3kGB3RipnPZUFpKbRbM0XsQJHMC+i5UD3VOd3t5OTncc9zE12wcDIhJ5oF6SJ7jaSi/u5j585hqhiritqIt7KufhUHK52N8hUYKcHKPe6ouZWIDHI49RTymBihjO/dec7ztptlKZQcNYMC1u6HqnDkIEMxVIVuNVlBCN+hZpvyY=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: pihole
