---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgDP1dpuS+DGkABDQXLVcCm4jHZTs1eyvJHSayztUo+UekfLUAQxhgNqxJgPzLRROcImDMQvJl2hugbiWZF6SwMYldnr+QcRqaLeU52/LNoryd15eBb6FHxLym4oC+G30dcJfWTA3ALsNw1vBNnxU8+l6zcBCNlg5p8ISqAa8Qx29rTRak+JcHWR3PZewKlPTLDKkaXrv+oRSfnE73tbNqnRcskdTMkfQcJlnL8H1+veyn7+2va7hpKtbLmk7iLvdGfw81B2OfeS71MwpbJLbBXbQer2JsuGsdsX0o++4M15SZtkg45FJZrOioxM6qU3n9qTy8bA1+Mr8KmTv4+e9/Ym8Y2F2UYW/o1RvXLDWVKzzaedbLd9kD6qyzv09opub8ueY30YDOoFK959J4/MZfwSVA4topF3KPFCSXUDn4/gcrX+a4xjeS5jVUL7aNbV/j+BljJZlusx14UM4oJDvjeh0xElHR0sBq74w1OPnik3jPB+6e5ijG5ivXv4M1pDYEUPUczlntePnA2VO7LXohwqekvnbxnnF6H2aZp8Ecdv26nSYWBk9yduo+MY2l2GQMHXanhqefeqjCwX9LCufUVHyk8KN77Yd0cRFUtsEhZj+Bo3DaL9z2DKu6+V8LDOKtjhs373VlT3ncxh1lPgXYB5HqXQQDD7nZrLlV408UK20Jd0szG5YBzob17d56WrpbSrOka2mrTGc4kqF7U=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: pihole
