---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  creationTimestamp: null
  name: pihole-secret
  namespace: pihole
spec:
  encryptedData:
    WEBPASSWORD: AgB6UrBXzlV4S86796Hew4/U4kNhTAW0o9wxYRJTo58KOgeMJ3uvfULx4+b1eVZA0m8Y1vwbwwlHyXHeW5GRKUQGLEq/zRfzhrmfVXeUA4VMrotGlee3ayOMe0JS4H3SMUeA5jcCbtIhm5UHERCBqeaPMNDmK6NCH4kPMafjH942zaKLdA5UuB4bJSE1tRmJpc9AIQ7VxTfc6C/zrGJiI4QiHpnwPE/A1aKaSfeN2yFrJgXhd9oLAu8av/PGv4B1zrPLZA++gvpu4m1iwrJ4H/Ge3stsc4S6v19jBK/cIWlRQhsICqM2YXdp0INSP6wZnVUBKpYQCu0oSbHydKw+V4XTYbDvC54yNvzZpp5lNA9+UrwkNJPJ2dxOBpz9qkaCWT99vD376lMniRLhocG14FzfmHcPFgsCS4bpTRo91Y/8DIjUnG/cDKyDF4YMJmh0GN8RoyMfVqHAQQaxhHOgskj6V3nWke21jhIgcJ8l7/MHkYouWrnAeeUaN1CdsT3OsYPuMmjoNPgZqgZfRxIF8qvL1HWBbt52RQglLckNvHvDB2hgSVRJj+cVXQbFDkpbPmAjdHLyYiITLGUgfk/74YUSUoK6JT4u++uhQDJBQ2PKC1fIicXDL6KKdUbBmk6KXyu1pmaFLmLKo2BqZalhiseUgF+AKB4uBzS1byGrQmkNNMQbN53l1CVPLf4JXG9DmbyWQvSFx8UVZVuPZLo=
  template:
    metadata:
      creationTimestamp: null
      name: pihole-secret
      namespace: pihole
