apiVersion: v1
kind: Service
metadata:
  name: pihole
  namespace: pihole
  labels:
    cilium-lb-pool: main-pool
spec:
  type: LoadBalancer
  externalTrafficPolicy: Cluster
  loadBalancerClass: "io.cilium/l2-announcer"
  selector:
    app: pihole
  ports:
    - name: dns-tcp
      port: 53
      targetPort: dns-tcp
      protocol: TCP
    - name: dns-udp
      port: 53
      targetPort: dns-udp
      protocol: UDP
    - name: http
      port: 80
      targetPort: http
      protocol: TCP
