apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: graylog
  namespace: graylog
spec:
  interval: 15m
  chart:
    spec:
      chart: graylog
      version: "12.1.2"
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
  install:
    remediation:
      retries: 3
  upgrade:
    remediation:
      retries: 3
  valuesFrom:
    - kind: ConfigMap
      name: graylog-values
      valuesKey: values.yaml
