apiVersion: ENC[AES256_GCM,data:FWI=,iv:J4jWwhQO4Em6jM1CpZYpbcTOfKtmTz1vq3yc37/kZ0Y=,tag:nuAczpIHJVsrIslkQHAo6A==,type:str]
kind: ENC[AES256_GCM,data:jw1xkAJKnhJ8PojCChI=,iv:sTUnmEWyu1bVUTs128NeKN4iS2eUBQ5HAqTfJ6JgdM8=,tag:n8Kgsr+ya8Lnif8AoTtrGA==,type:str]
metadata:
    name: ENC[AES256_GCM,data:dBFu7vmFO4U=,iv:p+I6f6YZwedymFfl8oKq7FIc7snfNzIiGT6zcblNZd0=,tag:2BkQ94k/xeyPkcFLA7aTvg==,type:str]
    namespace: ENC[AES256_GCM,data:nvzAMlVH1jc=,iv:a4moeXkEPb0zwcPrlz+XjZRtYiQCc2iUtQq4WS412FU=,tag:F2xpQPY87FlxQzOKjWux7g==,type:str]
sops:
    age:
        - recipient: age1ek6h5yd7d4qs49zyjhu2fsvpwm8a4nezl02gd5zj35cawca5udgqt9jp25
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYcGJlWXMzR1RDeG55RkFk
            NXA0Q3h0ZTBzdU5TUnU0QWxHaE8zakF2bmtBCmF5TWdqcHc1d0ZyUHJaTldTaVFh
            NCtoRWl3SzhnR1czTEFHczZadFI1ZncKLS0tIHhWV016cndpVms4SDdjWjlpd0lx
            YldQckJrTmdubmNCS29aV1djU3ljN0EKUY3cC0kNcXc+m/nsk+xgHvOaxQpCk0Rl
            9/YK589yspzmVzQ0ibFU/d6MNlag43XWXPVk3VxqwkxLHHbTdiDzJg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-04-05T14:14:04Z"
    mac: ENC[AES256_GCM,data:aNQgM88iWtUJP5qz5OgFL1ThAFRNZ8RBkF0WUSzi1Xd+xx0PsYQUIyjW28D3mTZgbie0M4q8jhR9KlS37nx8HLfvjXQ7/8jPOuAzGZa1JiuU3GzfG9RWxGbo/VZGERqAJdF5Fun1ISAWG8p7pnCQkm3MI0fDRdNAFlINd20fG0k=,iv:tjQZSRB6Ujnf2sJstTux/GZGvVnq8SGPDcAqD8wVrVw=,tag:GSRgZkWo2V3hr05gKO3I1g==,type:str]
    unencrypted_suffix: _unencrypted
    version: 3.12.1
