apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: sealed-secrets
  namespace: kube-system
spec:
  interval: 10m
  chart:
    spec:
      chart: sealed-secrets
      sourceRef:
        kind: HelmRepository
        name: bitnami
        namespace: flux-system
      version: "2.5.19"
  releaseName: sealed-secrets
  values:
    secretName: sealed-secrets-keyk5bt8
