apiVersion: v1
kind: Secret
metadata:
  name: graylog-secret
  namespace: graylog
stringData:
  GRAYLOG_PASSWORD_SECRET: "long-random-string"
  GRAYLOG_ROOT_PASSWORD_SHA2: "8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918"
