apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: pgadmin-secret
  namespace: pgadmin
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: vault-backend
    kind: ClusterSecretStore
  target:
    name: pgadmin-secret
    creationPolicy: Owner
  data:
  - secretKey: PGADMIN_DEFAULT_EMAIL
    remoteRef:
      key: kubernetes/pgadmin
      property: PGADMIN_DEFAULT_EMAIL
  - secretKey: PGADMIN_DEFAULT_PASSWORD
    remoteRef:
      key: kubernetes/pgadmin
      property: PGADMIN_DEFAULT_PASSWORD
