apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-pstgres-pvc
  namespace: wallabag-db
spec:
  accessMode:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi

