apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: wallabag-postgres-pvc
  namespace: wallabag-db
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 2Gi

