apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: cloudflared-config
  namespace: networking
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: aws-secret-store
    kind: ClusterSecretStore
  target:
    name: cloudflared-config 
    template:
      engineVersion: v2
      data:
        config.yaml: |
          tunnel: {{ .tunnel_id }}
          credentials-file: /etc/cloudflared/creds/credentials.json
          metrics: 0.0.0.0:2000
          no-autoupdate: true
          ingress:
            ingress:
            - hostname: codewithakay.dev
              service: http://cwkcv-service.cwk.svc.cluster.local:80
          # Add services here i.e.
            # - hostname: n8n.codewithakay.dev
            # - hostname: codewithakay.dev
            #   service: http://n8n.n8n.svc.cluster.local:5678
            - service: http_status:404
  data:
    - secretKey: tunnel_id
      remoteRef:
        key: homelab/kubernetes/cloudflare
        property: tunnel_id
